name: Test Secrets Configuration

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Docker Hub Username
      run: |
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "❌ DOCKERHUB_USERNAME is not set"
          exit 1
        else
          echo "✅ DOCKERHUB_USERNAME is set"
        fi
        
    - name: Test Docker Hub Token
      run: |
        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "❌ DOCKERHUB_TOKEN is not set"
          exit 1
        else
          echo "✅ DOCKERHUB_TOKEN is set"
        fi
        
    - name: Test SonarCloud Token
      run: |
        if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
          echo "❌ SONAR_TOKEN is not set"
          exit 1
        else
          echo "✅ SONAR_TOKEN is set"
        fi
        
    - name: Test Render Service ID
      run: |
        if [ -z "${{ secrets.RENDER_SERVICE_ID }}" ]; then
          echo "❌ RENDER_SERVICE_ID is not set"
          exit 1
        else
          echo "✅ RENDER_SERVICE_ID is set"
        fi
        
    - name: Test Render API Key
      run: |
        if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
          echo "❌ RENDER_API_KEY is not set"
          exit 1
        else
          echo "✅ RENDER_API_KEY is set"
        fi
        
    - name: All secrets configured
      run: |
        echo "🎉 All secrets are properly configured!"
